---
title: "chp5"
author: "George Oberle"
date: "May 2, 2015"
output: html_document
---

```{r}
library (sp)
library (rgdal)
library (rgeos)
library (maptools)
library (ggmap)
library (ggplot2)
library (mullenMisc)
library (magrittr)
library (stringr)
library (dplyr)
library (RColorBrewer)
library (igraph)

```


```{r}
early_learned <- read.csv("~/chp5/data/schol-soc-geocoded.csv")
silliman_societies <- read.csv("~/chp5/data/Scientific_Societies_1825_American_Journal_of_Science_and_Arts.csv")
bates_early_learned <-read.csv("~/chp5/data/Early Learned Societies Bates 2.csv")
scilearn <- read.csv ("~/chp5/data/scilearned.csv")
```

```{r}
t <- ggplot(silliman_societies, aes(x=Year.Established))
t + geom_histogram()
t + geom_histogram(binwidth = 3)

u <- ggplot (silliman_societies, aes(x=State))
u + geom_histogram()
u + geom_histogram() + ggtitle ("Scientific Societies 1826")+ ylab ("Total Established")
```



```{r}
typedate <- ggplot(early_learned, aes (x=Date.Established, fill=Society))
typedate+ geom_histogram(position= "stack", binwidth= 10) + theme(axis.text.x = element_text(face = "bold", angle = 60, hjust = 1, size = 8)) +ggtitle("Learned Societies by Date Established") + ylab("Total Established") + xlab ("Year Established")
```

```{r}
#Histogram of Total Learned Societies Established 1768-1848 by state.
n <- ggplot(early_learned, aes(x=State))
n + geom_histogram() + ggtitle("Learned Societies Established 1768-1848") + ylab("Total Established")
```

```{r}
tt <- ggplot(early_learned, aes(x=Date.Established))
tt + geom_histogram()
tt + geom_histogram(binwidth = 3)

date <- early_learned[ which(early_learned$Date.Established <1827), ]
datebates <- early_learned[ which(bates_early_learned$Date.Established <1827), ]

uu <- ggplot (early_learned, aes(x=State))
uu + geom_histogram()
u + geom_histogram() + ggtitle ("Learned Societies")+ ylab ("Total Established")

udate <- ggplot (date, aes(x=State))
udate + geom_histogram()
udate + geom_histogram() + ggtitle ("Learned Societies Before 1826")+ ylab ("Total Established")

```

```{r}
batesdate <- ggplot (bates_early_learned, aes(x=State))
batesdate + geom_histogram()
batesdate + geom_histogram() + ggtitle ("Scientific Societies Ralph Bates")+ ylab ("Total Established")

newdate <- ggplot (datebates, aes(x=State))
newdate + geom_histogram()
newdate + geom_histogram() + ggtitle ("Scientific Societies Before 1826 Ralph Bates")+ ylab ("Total Established")
```


```{r}
year <- ggplot(scilearn, aes(x=State, fill= Type ))
year + geom_histogram(position = "dodge", binwidth = 1) +
ggtitle("Comparison of Sillian's Scientific Survey with Scholarly Societies") + ylab("Total Institutions")
```


silliman_societies 
